// UploadGames.jsx
import React from "react";
import { ref, push } from "firebase/database";
import { database } from "./firebase";

const games = [
    {
        description:
            "Just Skip, Reverse, Draw and go Wild to get rid of your last card, And don't wait to jab ZUNO, or else your opponents will make your life hard",
        gameCategory: "Strategy",
        gameImage: "https://static.gamezop.com/ByQxJnp7qRB/cover.jpg",
        gameUrl: "https://9783.play.gamezop.com/g/ByQxJnp7qRB",
        slug: "ZUNO",
        metaUrl: "ZUNO",
        view: 23,
        howToPlay: "Placeholder: Tap the screen to play",
        whoCreated: "Placeholder: Innowise Group",
        playForFree: "Placeholder: You can play on our Website",
        mobileDesktop: "Placeholder: You can play on desktop or mobile",
    },
    {
        description:
            "These dragons from hell, under the witch's spell, are going to destroy the village you dwell! The only way to repel, is to show them the power of your shell!.",
        gameCategory: "Merge",
        gameImage: "https://static.gamezop.com/B1SmafkP5kQ/thumb.png",
        gameTitle: "Dragon Annihilation",
        gameUrl: "https://9783.play.gamezop.com/g/oh-yes",
        slug: "dragon-annihilation",
        metaUrl: "dragon-annihilation",
        view: 3,
        howToPlay: "Placeholder: Tap to merge dragons",
        whoCreated: "Placeholder: Gamezop",
        playForFree: "Placeholder: Play free online",
        mobileDesktop: "Placeholder: Available on mobile",
    },
    {
        description:
            "Balance between the right and the left wheels so that their colours match with the balls.",
        gameCategory: "Arcade",
        gameImage: "https://static.gamezop.com/SyFcNzAX6/cover.jpg",
        gameTitle: "Shade Shuffle",
        gameUrl: "https://9783.play.gamezop.com/g/SyFcNzAX6",
        slug: "Shade-Shuffle",
        metaUrl: "Shade-Shuffle",
        view: 3,
        howToPlay: "Placeholder: Tap left/right to balance",
        whoCreated: "Placeholder: Unknown",
        playForFree: "Placeholder: Play free on Gamezop",
        mobileDesktop: "Placeholder: Mobile and desktop",
    },
    {
        description:
            "You've got 3 wickets and an audience to impress! Go at it! Make as many runs as you can. Be careful of the bombs and eggs?!",
        gameCategory: "Sports & Racing",
        gameImage: "https://static.gamezop.com/BkzmafyPqJm/cover.jpg",
        gameTitle: "Cricket Gunda",
        gameUrl: "https://9783.play.gamezop.com/g/BkzmafyPqJm",
        slug: "Cricket-Gunda",
        metaUrl: "Cricket-Gunda",
        view: 3,
        howToPlay: "Placeholder: Tap to hit the ball",
        whoCreated: "Placeholder: Gamezop",
        playForFree: "Placeholder: Play for free",
        mobileDesktop: "Placeholder: Available on mobile",
    },
    {
        description:
            "The little trippers are out on an adventure. Change shapes and colors as you spiral across beautiful planetary landscapes.",
        gameCategory: "Strategy",
        gameImage: "https://static.gamezop.com/rkb--Io78Ux/cover.jpg",
        gameTitle: "Tiny Tripper",
        gameUrl: "api/game/g/rkb--Io78Ux",
        slug: "Tiny-Tripper",
        metaUrl: "Tiny-Tripper",
        view: 3,
        howToPlay: "Placeholder: Tap to change colors",
        whoCreated: "Placeholder: Unknown",
        playForFree: "Placeholder: Play now!",
        mobileDesktop: "Placeholder: Mobile and desktop",
    },
    {
        description:
            "Here's what a typical day in Texas would look like if the Martians landed on Earth! Shoot 'em all!",
        gameCategory: "Puzzle & Logic",
        gameImage: "https://static.gamezop.com/SyTeia3fOeZ/cover.jpg",
        gameTitle: "Cowboy vs. Martians",
        gameUrl: "https://9783.play.gamezop.com/g/SyTeia3fOeZ",
        slug: "Cowboy-vs-Martians",
        metaUrl: "Cowboy-vs-Martians",
        view: 3,
        howToPlay: "Placeholder: Tap to shoot",
        whoCreated: "Placeholder: Gamezop",
        playForFree: "Placeholder: Free to play",
        mobileDesktop: "Placeholder: Play on mobile",
    },
    {
        description:
            "See beautiful landscapes unfold as you navigate the twists and turns of these endless roads: just make sure you only clash with balls of your own colour.",
        gameCategory: "Adventure",
        gameImage: "https://static.gamezop.com/B1JBaM1D9y7/cover.jpg",
        gameTitle: "Colour Chase",
        gameUrl: "https://9783.play.gamezop.com/g/B1JBaM1D9y7",
        slug: "Colour-Chase",
        metaUrl: "Colour-Chase",
        view: 3,
        howToPlay: "Placeholder: Tap to change lanes",
        whoCreated: "Placeholder: Unknown",
        playForFree: "Placeholder: Play for free now",
        mobileDesktop: "Placeholder: Available on desktop and mobile",
    },
    {
        description:
            "Numbers merge to make higher numbers, stars blast when merged. The best match-3 HTML5 game!",
        gameCategory: "Puzzle & Logic",
        gameImage: "https://static.gamezop.com/HJXei0j/cover.jpg",
        gameTitle: "Cyberfusion",
        gameUrl: "https://9783.play.gamezop.com/g/HJXei0j",
        slug: "Cyber-fusion",
        metaUrl: "Cyber-fusion",
        view: 3,
        howToPlay: "Placeholder: Tap to merge numbers",
        whoCreated: "Placeholder: Gamezop",
        playForFree: "Placeholder: Play free",
        mobileDesktop: "Placeholder: Play online",
    },
    {
        description:
            "Help the tiny monster jump higher from platform to platform. Try to eat all apples in this endless game.",
        gameCategory: "Arcade",
        gameImage: "https://static.gamezop.com/SyjAFr-dE/cover.jpg",
        gameTitle: "Jom Jom Jump",
        gameUrl: "https://9783.play.gamezop.com/g/SyjAFr-dE",
        slug: "Jom-Jom-Jump",
        metaUrl: "Jom-Jom-Jump",
        view: 3,
        howToPlay: "Placeholder: Tap to jump",
        whoCreated: "Placeholder: Unknown",
        playForFree: "Placeholder: Enjoy free gameplay",
        mobileDesktop: "Placeholder: Available on mobile devices",
    },
    {
        description:
            "It's a game of luck! What do you instincts say - will it be a high card, or a low card? ",
        gameCategory: "Puzzle & Logic",
        gameImage: "https://static.gamezop.com/H1eGU64XRg/cover.jpg",
        gameTitle: "High or Low",
        gameUrl: "https://9783.play.gamezop.com/g/H1eGU64XRg",
        slug: "High-or-Low",
        metaUrl: "High-or-Low",
        view: 3,
        howToPlay: "Placeholder: Guess high or low",
        whoCreated: "Placeholder: Gamezop",
        playForFree: "Placeholder: No cost to play",
        mobileDesktop: "Placeholder: Compatible on desktop and mobile",
    },
    {
        description:
            "Here's the dumbest soccer game ever! How well can you play without turning around?",
        gameCategory: "Sports & Racing",
        gameImage: "https://static.gamezop.com/BJ8Wb8j7ILx/cover.jpg",
        gameTitle: "Soccer Jerks",
        gameUrl: "https://9783.play.gamezop.com/g/BJ8Wb8j7ILx",
        slug: "Soccer-Jerks",
        metaUrl: "Soccer-Jerks",
        view: 3,
        howToPlay: "Placeholder: Tap to move and play",
        whoCreated: "Placeholder: Unknown",
        playForFree: "Placeholder: Totally free",
        mobileDesktop: "Placeholder: Works on mobiles",
    },
    {
        description:
            "Jump from floor to floor, avoid the ghosts! How high can you climb in this endless game?",
        gameCategory: "Adventure",
        gameImage: "https://static.gamezop.com/BkXW1a__/cover.jpg",
        gameTitle: "Jimbo Jump",
        gameUrl: "https://9783.play.gamezop.com/g/BkXW1a___",
        slug: "Jimbo-Jump",
        metaUrl: "Jimbo-Jump",
        view: 3,
        howToPlay: "Placeholder: Jump over floors, avoid the ghost",
        whoCreated: "Placeholder: Innowise",
        playForFree: "Placeholder: Free",
        mobileDesktop: "Placeholder: Tablet, phone, and desktop",
    },
    {
        description:
            "Bring out the cowboy in you and keep a level head while you shoot down as many bottles as you can. Keep an eye out for the red ones!",
        gameCategory: "Action",
        gameImage: "https://static.gamezop.com/B1fSpMkP51m/cover.jpg",
        gameTitle: "Bottle Shoot",
        gameUrl: "https://9783.play.gamezop.com/g/B1fSpMkP51m",
        slug: "Bottle-Shoot",
        metaUrl: "Bottle-Shoot",
        view: 3,
        howToPlay: "Tap to shoot, be careful of the red ones",
        whoCreated: "Gamezop",
        playForFree: "Free forever",
        mobileDesktop: "Availalble on any mobile devices",
    },
    {
        description:
            "Compete with thousands of players across cricket, history, Bollywood and more categories in Gamezop's Quiz Champions and win real money!",
        gameCategory: "Puzzle & Logic",
        gameImage: "https://static.gamezop.com/Sy8y2aQ9CB/cover.jpg",
        gameTitle: "Quiz Champions",
        gameUrl: "https://9783.play.gamezop.com/g/Sy8y2aQ9CB",
        slug: "Quiz-Champions",
        metaUrl: "Quiz-Champions",
        view: 3,
        howToPlay: "Use all your knowlege to win.",
        whoCreated: "Gamezop",
        playForFree: "It's free",
        mobileDesktop: "Available on desktop and mobile",
    },
    {
        description: "Action",
        gameCategory:
            "Guide the ninja to move swiftly between pointed obstacles and climb reach great heights!",
        gameImage: "https://static.gamezop.com/S1kGWUim8Ux/cover.jpg",
        gameTitle: "Shadow Run",
        gameUrl: "https://9783.play.gamezop.com/g/S1kGWUim8Ux",
        slug: "Shadow-Run",
        metaUrl: "Shadow-Run",
        view: 3,
        howToPlay:
            "Guide the ninja to move swiftly between pointed obstacles and climb reach great heights!",
        whoCreated: "Hypersonic",
        playForFree: "Free on Poki.",
        mobileDesktop: "Both desktop and mobile",
    },
    {
        description:
            "Test your marksmanship by shooting down boxes that come your way. Beware of surprises!",
        gameCategory: "Arcade",
        gameImage: "https://static.gamezop.com/B19EafJP9JX/cover.jpg",
        gameTitle: "Spinning Shooter",
        gameUrl: "https://9783.play.gamezop.com/g/B19EafJP9JX",
        slug: "Spinning-Shooter",
        metaUrl: "Spinning-Shooter",
        view: 3,
        howToPlay: "Keep a balance head and test you marksmanship!",
        whoCreated: "Innowise Group",
        playForFree: "Can play for free.",
        mobileDesktop: "Works on mobile devices and tablets as well",
    },
    {
        description:
            "Cute bunny is a great chap but has one problem: can only eat fruits if in a set of 3! Help at will!",
        gameCategory: "Puzzle & Logic",
        gameImage: "https://static.gamezop.com/BkpeAKrW_E/cover.jpg",
        gameTitle: "Veggi Rabbit",
        gameUrl: "https://9783.play.gamezop.com/g/BkpeAKrW_E",
        slug: "Veggi-Rabbit",
        metaUrl: "Veggi-Rabbit",
        view: 3,
        howToPlay: "Help the rabbit to eat veggi in a set of 3",
        whoCreated: "Korgi Inc",
        playForFree: "100% Free on Gamezop",
        mobileDesktop: "Available on any mobile devices and tablets as well",
    },
    {
        description:
            "Enjoy the calming beauty of Mahjong set in a Scandinavian landscape, with relaxing puzzles, serene Nordic backdrops, and a peaceful atmosphere for every match.",
        gameCategory: "Puzzle & Logic",
        gameImage: "https://static.gamezop.com/JVhRZNwly/cover.jpg",
        gameTitle: "Mahjong At Home: Scandinavian Edition",
        gameUrl: "https://9783.play.gamezop.com/g/JVhRZNwly",
        slug: "Mahjong At Home: Scandinavian Edition",
        metaUrl: "Mahjong At Home: Scandinavian Edition",
        view: 3,
        howToPlay: "Tap on the tile.",
        whoCreated: "Corgi LTD.",
        playForFree: "Now! At Gamezop.",
        mobileDesktop: "Mobile & desktop",
    },
    {
        description:
            "The war is here. It's the need of the hour. Block by block, tower after tower, it's time you prove your tank's dominance & power!",
        gameCategory: "Action",
        gameImage: "https://static.gamezop.com/8WGtd7TLH/cover.jpg",
        gameTitle: "Tower Buster",
        gameUrl: "https://9783.play.gamezop.com/g/TowerBuster",
        slug: "Tower-Buster",
        metaUrl: "Tower-Buster",
        view: 3,
        howToPlay: "Destroy all your opponents!",
        whoCreated: "Gamedev",
        playForFree: "Click right now!",
        mobileDesktop: "Mobile",
    },
    {
        description:
            "Wrong-way driver on your lane? Be quick with the lane changes for you blink and you miss!",
        gameCategory: "Sports & Racing",
        gameImage: "https://static.gamezop.com/4kZgf_1z-9l/cover.jpg",
        gameTitle: "Lane Battles",
        gameUrl: "https://9783.play.gamezop.com/g/4kZgf_1z-9l",
        slug: "Lane-Battles",
        metaUrl: "Lane-Battles",
        view: 3,
        howToPlay: "Be quick!",
        whoCreated: "Gamedev",
        playForFree: "Play it all day long!",
        mobileDesktop: "Mobile",
    },
    {
        description:
            "Choose your ninja and collect and munch on the delicious crunchy apples in this endless game.",
        gameCategory: "Action",
        gameImage: "https://static.gamezop.com/EJnzu1fb9g/cover.jpg",
        gameTitle: "Crunching Ninjas",
        gameUrl: "https://9783.play.gamezop.com/g/EJnzu1fb9g",
        slug: "Crunching-Ninjas",
        metaUrl: "Crunching-Ninjas",
        view: 3,
        howToPlay: "Collect and munch!",
        whoCreated: "Gamezop",
        playForFree: "Always free",
        mobileDesktop: "Mobile",
    },
    {
        description:
            "Combine jelly shapes of the same color by sliding the jellies together. Use fewest possible moves.",
        gameCategory: "Puzzle & Logic",
        gameImage: "https://static.gamezop.com/rJsWV8aIa-l/cover.jpg",
        gameTitle: "Jelly Doods",
        gameUrl: "https://9783.play.gamezop.com/g/rJsWV8aIa-l",
        slug: "Jelly-Doods",
        metaUrl: "Jelly-Doods",
        view: 3,
        howToPlay: "Find the jelly of the same color",
        whoCreated: "Korgi Ltd.",
        playForFree: "No cost!",
        mobileDesktop: "Yes!",
    },
    {
        description:
            "Remove wooden objects off the game board to get a treasure chest next to the magician.",
        gameCategory: "Puzzle & Logic",
        gameImage: "https://static.gamezop.com/B1MXhUFQke/cover.jpg",
        gameTitle: "Tower Loot",
        gameUrl: "https://9783.play.gamezop.com/g/B1MXhUFQke",
        slug: "Tower-Loot",
        metaUrl: "Tower-Loot",
        view: 3,
        howToPlay: "Collect the tresaure chest",
        whoCreated: "Korgi Inc",
        playForFree: "Click to play!",
        mobileDesktop: "Phone and desktop",
    },
    {
        description:
            "Trolls are taking to the ring for a Championship! Jump right into the action in this boxing game.",
        gameCategory: "Action",
        gameImage: "https://static.gamezop.com/Hy2xAKHb_V/cover.jpg",
        gameTitle: "Troll Boxing",
        gameUrl: "https://9783.play.gamezop.com/g/Hy2xAKHb_V",
        slug: "Troll-Boxing",
        metaUrl: "Troll-Boxing",
        view: 3,
        howToPlay: "Have fun while playng!",
        whoCreated: "Korgi LTD.",
        playForFree: "Gamezop",
        mobileDesktop: "Mobile",
    },
    {
        description:
            "The best Pai Gow Poker online! Bring out your high hands and low hands, and beat the dealer.",
        gameCategory: "Strategy",
        gameImage: "https://static.gamezop.com/SkGIa4X0l/cover.jpg",
        gameTitle: "Pai Gow Poker",
        gameUrl: "https://9783.play.gamezop.com/g/SkGIa4X0l",
        slug: "Pai-Gow-Poker",
        metaUrl: "Pai-Gow-Poker",
        view: 3,
        howToPlay: "Show your high and low hand",
        whoCreated: "Korgi Inc",
        playForFree: "Always on Gamezop",
        mobileDesktop: "Phone and desktop",
    },
    {
        description:
            "Help cute creatures to climb into their tubes in this colourfully cute puzzle game for young and old.",
        gameCategory: "Puzzle & Logic",
        gameImage: "https://static.gamezop.com/SJghvtd2_/cover.jpg",
        gameTitle: "Drop Me",
        gameUrl: "https://9783.play.gamezop.com/g/SJghvtd2_",
        slug: "Drop-Me",
        metaUrl: "Drop-Me",
        view: 3,
        howToPlay: "Climb into there tubes",
        whoCreated: "Gamezop",
        playForFree: "For young and old",
        mobileDesktop: "Phone and Tablet",
    },
    {
        description:
            "Puzzle game in which you play an alien mom hatching slimy, oozing eggs across several levels.",
        gameCategory: "Puzzle & Logic",
        gameImage: "https://static.gamezop.com/r1Xm38FQkl/cover.jpg",
        gameTitle: "Alien Kindergarten",
        gameUrl: "https://9783.play.gamezop.com/g/r1Xm38FQkl",
        slug: "Alien-Kindergarten",
        metaUrl: "Alien-Kindergarten",
        view: 3,
        howToPlay: "Hatching egg across several levels",
        whoCreated: "Korgi Inc",
        playForFree: "From young and old",
        mobileDesktop: "Phone and Desktop",
    },
    {
        description:
            "Wade through space and keep your space ship away from flying saucers.",
        gameCategory: "Adventure",
        gameImage: "https://static.gamezop.com/B1Gbjphf_gZ/cover.jpg",
        gameTitle: "Saucer Dodge",
        gameUrl: "https://9783.play.gamezop.com/g/B1Gbjphf_gZ",
        slug: "Saucer-Dodge",
        metaUrl: "Saucer-Dodge",
        view: 3,
        howToPlay: "Tap anywhere to play",
        whoCreated: "Gamezop",
        playForFree: "From Gamezop",
        mobileDesktop: "Works on Mobile and Desktop",
    },
    {
        description:
            "Don't let the lady out of sight, or you'll lose the game. How attentive are you?",
        gameCategory: "Strategy",
        gameImage: "https://static.gamezop.com/HyZMUTVQRe/cover.jpg",
        gameTitle: "Where's the Ace?",
        gameUrl: "https://9783.play.gamezop.com/g/HyZMUTVQRe",
        slug: "Where's-the-Ace?",
        metaUrl: "Where's-the-Ace",
        view: 3,
        howToPlay: "It's a strategy!",
        whoCreated: "Unknown",
        playForFree: "Works on desktop",
        mobileDesktop: "Not mobile",
    },
    {
        description:
            "The canon's loaded and the knight's ready! Bounce through your flight while avoiding the onslaught of monsters.",
        gameCategory: "Adventure",
        gameImage: "https://static.gamezop.com/rkYbNLTIT-x/cover.jpg",
        gameTitle: "Knight Ride",
        gameUrl: "https://9783.play.gamezop.com/g/rkYbNLTIT-x",
        slug: "Knight-Ride",
        metaUrl: "Knight-Ride",
        view: 3,
        howToPlay: "Avoid the monsters!",
        whoCreated: "Innowise Group",
        playForFree: "Have fun on Gamezop!",
        mobileDesktop: "Mobile and desktop",
    },
    {
        description:
            "Shoot the bad guys that are occupying the tower. Take them down and be mindful of the civilians.",
        gameCategory: "Action",
        gameImage: "https://static.gamezop.com/NJ8gGuyMZ5e/cover.jpg",
        gameTitle: "Pie Attack",
        gameUrl: "https://9783.play.gamezop.com/g/NJ8gGuyMZ5e",
        slug: "Pie-Attack",
        metaUrl: "Pie-Attack",
        view: 3,
        howToPlay: "Take them down and be mindful of the civilians.",
        whoCreated: "Innowise Group",
        playForFree: "Can play for free.",
        mobileDesktop: "Works on mobile devices and tablets as well",
    },
    {
        description:
            "Dive into an underwater world full of beauty where you can collect coins too... just a little bit of danger.",
        gameCategory: "Adventure",
        gameImage: "https://static.gamezop.com/SJz7-kTud/cover.jpg",
        gameTitle: "Submarine Dash",
        gameUrl: "https://9783.play.gamezop.com/g/SJz7-kTud",
        slug: "Submarine-Dash",
        metaUrl: "Submarine-Dash",
        view: 3,
        howToPlay:
            "Dive into an underwater world full of beauty where you can collect coins too... just a little bit of danger.",
        whoCreated: "Hypersonic",
        playForFree: "Free on Poki.",
        mobileDesktop: "Both desktop and mobile",
    },
    {
        description:
            "Grow fish to convert monsters into friends! Addictive arcade game with funny sea creatures.",
        gameCategory: "Adventure",
        gameImage: "https://static.gamezop.com/ry3vtunu/cover.jpg",
        gameTitle: "Battle Fish",
        gameUrl: "https://9783.play.gamezop.com/g/ry3vtunu",
        slug: "Battle-Fish",
        metaUrl: "Battle-Fish",
        view: 3,
        howToPlay:
            "Grow fish to convert monsters into friends! Addictive arcade game with funny sea creatures.",
        whoCreated: "Innowise Group",
        playForFree: "Can play for free.",
        mobileDesktop: "Works on mobile devices and tablets as well",
    },
    {
        description:
            "Help people across the streets, watch out for gaps in traffic and make sure nobody gets hit by cars.",
        gameCategory: "Strategy",
        gameImage: "https://static.gamezop.com/r1z-eQ8nq/cover.jpg",
        gameTitle: "Road Safety",
        gameUrl: "https://9783.play.gamezop.com/g/r1z-eQ8nq",
        slug: "Road-Safety",
        metaUrl: "Road-Safety",
        view: 3,
        howToPlay:
            "Help people across the streets, watch out for gaps in traffic and make sure nobody gets hit by cars.",
        whoCreated: "Innowise Group",
        playForFree: "Can play for free.",
        mobileDesktop: "Works on mobile devices and tablets as well",
    },
    {
        description:
            "Play the timeless Solitaire game in an Algerian desert setting! This version of Solitaire has 2 decks for double the challenge and double the punch!",
        gameCategory: "Strategy",
        gameImage: "https://static.gamezop.com/rJu76zkD917/cover.jpg",
        gameTitle: "Algerian-Solitaire",
        gameUrl: "https://9783.play.gamezop.com/g/rJu76zkD917",
        slug: "Algerian-Solitaire",
        metaUrl: "Algerian-Solitaire",
        view: 3,
        howToPlay: "Tap on the tile.",
        whoCreated: "Corgi LTD.",
        playForFree: "Can play for free on Poki.",
        mobileDesktop: "Both mobile and desktop",
    },
    {
        description:
            "Hop, jump, and bounce over obstacles and collect the purple star boxes in each level of this game.",
        gameCategory: "Strategy",
        gameImage: "https://static.gamezop.com/Sy6RYB-u4/cover.jpg",
        gameTitle: "Little-Bouncing-Guys",
        gameUrl: "https://9783.play.gamezop.com/g/Sy6RYB-u4",
        slug: "Little-Bouncing-Guys",
        metaUrl: "Little-Bouncing-Guys",
        view: 3,
        howToPlay: "Hop, jump, and bounce over obstacles",
        whoCreated: "Gamedev",
        playForFree: "Click to play!",
        mobileDesktop: "Mobile or desktop",
    },
    {
        description:
            "You have to make the Knife flip from pillar to post! The objective of the game is simple: don't fall down.",
        gameCategory: "Adventure",
        gameImage: "https://static.gamezop.com/H1PJn6mqAr/cover.jpg",
        gameTitle: "Knife Flip",
        gameUrl: "https://9783.play.gamezop.com/g/H1PJn6mqAr",
        slug: "Knife-Flip",
        metaUrl: "Knife-Flip",
        view: 3,
        howToPlay: "Objective is simple, don't fall down",
        whoCreated: "Unknown",
        playForFree: "Available for you!",
        mobileDesktop: "Works on Phone",
    },
    {
        description:
            "Match bears of the same color to clear the level. P.S. Don't play this game when you are hungry.",
        gameCategory: "Strategy",
        gameImage: "https://static.gamezop.com/SJcRYSbu4/cover.jpg",
        gameTitle: "Jelly Bears",
        gameUrl: "https://9783.play.gamezop.com/g/SJcRYSbu4",
        slug: "Jelly-Bears",
        metaUrl: "Jelly-Bears",
        view: 3,
        howToPlay: "Don't play this game when you are hungry.",
        whoCreated: "Gamedev",
        playForFree: "Gamezop",
        mobileDesktop: "Desktop and phone",
    },
    {
        description:
            "Here's a Tic Tac Toe game with a twist! Play in a 11x11 grid, and match 5 to win - vertically, horizontally or diagonally! Create your own tricks to beat the opponent!",
        gameCategory: "Puzzle & Logic",
        gameImage: "https://static.gamezop.com/Hk2yhp7cCH/cover.jpg",
        gameTitle: "Tic Tac Toe 11",
        gameUrl: "https://9783.play.gamezop.com/g/Hk2yhp7cCH",
        slug: "TicTacToe-11",
        metaUrl: "TicTacToe-11",
        view: 3,
        howToPlay: "Create your own tricks to beat the opponent",
        whoCreated: "Gamezop",
        playForFree: "Totally free",
        mobileDesktop: "Works on mobiles",
    },
    {
        description:
            "Switch gravity with a touch and avoid obstacles. Remember to get some sushi for extra points!",
        gameCategory: "Adventure",
        gameImage: "https://static.gamezop.com/SysZvGUt_ye/cover.jpg",
        gameTitle: "Snappy Spy",
        gameUrl: "https://9783.play.gamezop.com/g/SysZvGUt_ye",
        slug: "Snappy-Spy",
        metaUrl: "Snappy-Spy",
        view: 3,
        howToPlay: "Switch gravity with a touch and avoid obstacles.",
        whoCreated: "Innowise Group",
        playForFree: "All free on GZ",
        mobileDesktop: "Yes mobile",
    },
    {
        description:
            "It's time for a juicy, jivy Fiesta of Fruits. Merge the fruits to get the elusive Melons. Collect them all to become the fruit baron!",
        gameCategory: "Arcade",
        gameImage: "https://static.gamezop.com/mKZZW9NXW/cover.jpg",
        gameTitle: "Fruity Fiesta",
        gameUrl: "https://9783.play.gamezop.com/g/mKZZW9NXW",
        slug: "Fruity-Fiesta",
        metaUrl: "Fruity-Fiesta",
        view: 3,
        howToPlay: "You know how to play!",
        whoCreated: "Korgi Inc",
        playForFree: "From Gamezop",
        mobileDesktop: "Desktop and Phone",
    },
    {
        description:
            "Bounce off the platforms and make as many jumps as you can in this amazing 3D game!",
        gameCategory: "Arcade",
        gameImage: "https://static.gamezop.com/H1Tz6z1Dqym/cover.jpg",
        gameTitle: "Bouncy",
        gameUrl: "https://9783.play.gamezop.com/g/H1Tz6z1Dqym",
        slug: "Bouncy",
        metaUrl: "Bouncy",
        view: 3,
        howToPlay: "Make as many jumps as you can in this amazing 3D game!",
        whoCreated: "Gamedev",
        playForFree: "It is always free",
        mobileDesktop: "For desk and phone",
    },
    {
        description:
            "There's a group of chickens that need to cross the road, and they need to do that quick. Just try and avoid blood!",
        gameCategory: "Adventure",
        gameImage: "https://static.gamezop.com/rJ57aMJDcJm/cover.jpg",
        gameTitle: "Go Chicken Go",
        gameUrl: "https://9783.play.gamezop.com/g/rJ57aMJDcJm",
        slug: "GoChicken-Go",
        metaUrl: "GoChicken-Go",
        view: 3,
        howToPlay: "Help chickens to cross the road quickly!",
        whoCreated: "Innowise Group",
        playForFree: "Always",
        mobileDesktop: "Smart-devices",
    },
    {
        description:
            "Juicy, tasty, match-3 madness. Prove your skills and match as many fruits as possible.",
        gameCategory: "Puzzle & Logic",
        gameImage: "https://static.gamezop.com/H1lZem8hq/cover.jpg",
        gameTitle: "Juicy Dash",
        gameUrl: "https://9783.play.gamezop.com/g/H1lZem8hq",
        slug: "Juicy-Dash",
        metaUrl: "Juicy-Dash",
        view: 3,
        howToPlay: "Match as many fruits as possible",
        whoCreated: "Gamezop",
        playForFree: "Free to play",
        mobileDesktop: "Device Agnostic!",
    },
    {
        description:
            "Swipe the screen to chop fruits but don't hit the bombs! So unsheathe your sword and get ready to play the most fun fruit slice game online.",
        gameCategory: "Arcade",
        gameImage: "https://static.gamezop.com/rkWfy2pXq0r/cover.jpg",
        gameTitle: "Fruit Chop",
        gameUrl: "https://9783.play.gamezop.com/g/rkWfy2pXq0r",
        slug: "Fruit-Chop",
        metaUrl: "Fruit-Chop",
        view: 3,
        howToPlay: "Chop as many fruit as possible, don't touch the bomb",
        whoCreated: "Korgi LTD.",
        playForFree: "For all users",
        mobileDesktop: "Desktop and Phone",
    },
    {
        description:
            "Poor creature is stranded on unexplored land. Hop along to explore a beautiful galactic setup!",
        gameCategory: "Adventure",
        gameImage: "https://static.gamezop.com/HJD9VMRQa/cover.jpg",
        gameTitle: "Astro Knot",
        gameUrl: "https://9783.play.gamezop.com/g/HJD9VMRQa",
        slug: "Astro-Knot",
        metaUrl: "Astro-Knot",
        view: 3,
        howToPlay: "Explore a beautiful galactic setup!",
        whoCreated: "Dev",
        playForFree: "At Gamezop",
        mobileDesktop: "Desktop and mobile",
    },
    {
        description:
            "In this addictive game, smartly find the nearest gaps for the ball to pass through. Be quick!",
        gameCategory: "Arcade",
        gameImage: "https://static.gamezop.com/ByGqEfCXa/cover.jpg",
        gameTitle: "Falling Through",
        gameUrl: "https://9783.play.gamezop.com/g/ByGqEfCXa",
        slug: "Falling-Through",
        metaUrl: "Falling-Through",
        view: 3,
        howToPlay: "Be quick and smart!",
        whoCreated: "Gamezop",
        playForFree: "At anytime",
        mobileDesktop: "Works everywhere",
    },
    {
        description:
            "Help the animals hop from one twig to the other, without letting the rings touch the wood!",
        gameCategory: "Arcade",
        gameImage: "https://static.gamezop.com/4y6efOyf-5g/cover.jpg",
        gameTitle: "Bouncing-Beasts",
        gameUrl: "https://9783.play.gamezop.com/g/4y6efOyf-5g",
        slug: "Bouncing-Beasts",
        metaUrl: "Bouncing-Beasts",
        view: 3,
        howToPlay: "Don't let the rings touch the wood!",
        whoCreated: "Gamezop",
        playForFree: "You can play always",
        mobileDesktop: "Table and Phones",
    },
    {
        description:
            "Clear rows and columns before the numbers get to 0. Keep an eye on the progress bar to unlock special power ups!",
        gameCategory: "Puzzle & Logic",
        gameImage: "https://static.gamezop.com/S1Wrpf1v5ym/cover.jpg",
        gameTitle: "Box Crush",
        gameUrl: "https://9783.play.gamezop.com/g/S1Wrpf1v5ym",
        slug: "Box-Crush",
        metaUrl: "Box-Crush",
        view: 3,
        howToPlay: "Keep an eye on the progress bar",
        whoCreated: "Corgi Inc",
        playForFree: "Enjoy free",
        mobileDesktop: "All devices",
    },
    {
        description:
            "Dribble the football through the adventures of this game: through fielders and defenders, through pigs and electric poles! Just don't lose!",
        gameCategory: "Sports & Racing",
        gameImage: "https://static.gamezop.com/r1z13aXqAB/cover.jpg",
        gameTitle: "Flappy Foot Chinko",
        gameUrl: "https://9783.play.gamezop.com/g/r1z13aXqAB",
        slug: "FlappyFoot-Chinko",
        metaUrl: "FlappyFoot-Chinko",
        view: 3,
        howToPlay: "Dribble the football!",
        whoCreated: "Korgi INC",
        playForFree: "All our services are free to use",
        mobileDesktop: "All devices",
    },
    {
        description:
            "Hungry dragons have caged the birds of the realm. Join Pebble Boy, the Orc, to set them free.",
        gameCategory: "Strategy",
        gameImage: "https://static.gamezop.com/H1TbVUa8aWe/cover.jpg",
        gameTitle: "Pebble Boy",
        gameUrl: "https://9783.play.gamezop.com/g/H1TbVUa8aWe",
        slug: "Pebble-Boy",
        metaUrl: "Pebble-Boy",
        view: 3,
        howToPlay: "Find the birds from the game!",
        whoCreated: "Gamezop",
        playForFree: "You can play on Gamezop",
        mobileDesktop: "Phone and Tablet",
    },
    {
        description:
            "Don't let the grid fill up! Fit all the pieces in this brain challenging puzzle game!",
        gameCategory: "Puzzle&Logic",
        gameImage: "https://static.gamezop.com/41FZfdyG-5x/cover.jpg",
        gameTitle: "1212!",
        gameUrl: "https://9783.play.gamezop.com/g/41FZfdyG-5x",
        slug: "1212!",
        metaUrl: "1212!",
        view: 3,
        howToPlay: "Fit all the pieces in this brain challenging puzzle game!",
        whoCreated: "Gamedev",
        playForFree: "Free!",
        mobileDesktop: "Mobile or Tablet",
    },
    {
        description:
            "Collect as may fish as possible but avoid falling in the icy cold water. Hop your way to endless fun.",
        gameCategory: "Adventure",
        gameImage: "https://static.gamezop.com/HJee0YHZ_E/cover.jpg",
        gameTitle: "Penguin Skip",
        gameUrl: "https://9783.play.gamezop.com/g/HJee0YHZ_E",
        slug: "Penguin-Skip",
        metaUrl: "Penguin-Skip",
        view: 3,
        howToPlay: "Do not fall in the icy cold water!",
        whoCreated: "Hypersonic",
        playForFree: "You can click now and play!",
        mobileDesktop: "Smart device",
    },
    {
        description:
            "Aim the football at the crossbar - how hard can it be, right? Try scoring 100 in this game to find out!",
        gameCategory: "Sports & Racing",
        gameImage: "https://static.gamezop.com/H1CWk36mq0S/cover.jpg",
        gameTitle: "Crossbar Shots",
        gameUrl: "https://9783.play.gamezop.com/g/H1CWk36mq0S",
        slug: "Crossbar-Shots",
        metaUrl: "Crossbar-Shots",
        view: 3,
        howToPlay: "Easy if you know how, right?",
        whoCreated: "Hypersonic",
        playForFree: "At Gamezop",
        mobileDesktop: "Desktop or phone",
    },
    {
        description:
            "Run and find the best trajectory to dodge obstacles. Don't let those quarterbacks take the ball!",
        gameCategory: "Sports & Racing",
        gameImage: "https://static.gamezop.com/SkJf58Ouf0/cover.jpg",
        gameTitle: "Dribble Kings",
        gameUrl: "https://9783.play.gamezop.com/g/SkJf58Ouf0",
        slug: "Dribbl-Kings",
        metaUrl: "Dribble-Kings",
        view: 3,
        howToPlay: "Don't let those quarterbacks take the ball!",
        whoCreated: "Gamezop",
        playForFree: "Totally free",
        mobileDesktop: "All devices",
    },
    {
        description:
            "Colourful and modern snake game with snazzier enemies and much cooler movements!",
        gameCategory: "Strategy",
        gameImage: "https://static.gamezop.com/BJlg94zA76/cover.jpg",
        gameTitle: "Zigzag Clash",
        gameUrl: "https://9783.play.gamezop.com/g/BJlg94zA76",
        slug: "Zigzag-Clash",
        metaUrl: "Zigzag-Clash",
        view: 3,
        howToPlay: "Snake game!",
        whoCreated: "Gamedev",
        playForFree: "Click right now to play!",
        mobileDesktop: "Mobile and desktop",
    },
    {
        description:
            "Creepy spiders and bleak platforms leave no room for error as you set out to save your love!",
        gameCategory: "Adventure",
        gameImage: "https://static.gamezop.com/rJJMVIa8p-x/cover.jpg",
        gameTitle: "Sticky Goo",
        gameUrl: "https://9783.play.gamezop.com/g/rJJMVIa8p-x",
        slug: "Sticky-Goo",
        metaUrl: "Sticky-Goo",
        view: 3,
        howToPlay: "No room for errors!",
        whoCreated: "Gamezop",
        playForFree: "Come here and play now!",
        mobileDesktop: "Tablet, phone and notebook",
    },
    {
        description:
            "Slide tiles in any direction in this mathematical puzzle game to make identical digits converge.",
        gameCategory: "Puzzle & Logic",
        gameImage: "https://static.gamezop.com/NyM_JGWcx/cover.jpg",
        gameTitle: "2048",
        gameUrl: "https://9783.play.gamezop.com/g/NyM_JGWcx",
        slug: "2048",
        metaUrl: "2048",
        view: 3,
        howToPlay: "Slide tiles!",
        whoCreated: "Hypersonic",
        playForFree: "Have fun for free!",
        mobileDesktop: "You can play in anywhere!",
    },
    {
        description:
            "The best Blackjack game online! Score more than your opponent but keep under 21 to win!",
        gameCategory: "Strategy",
        gameImage: "https://static.gamezop.com/H13-Z8sQILx/cover.jpg",
        gameTitle: "Blackjack 21 Pro",
        gameUrl: "https://9783.play.gamezop.com/g/H13-Z8sQILx",
        slug: "Blackjack21-Pro",
        metaUrl: "Blackjack21-Pro",
        view: 3,
        howToPlay: "Score more than your opponent but keep under 21",
        whoCreated: "Gamdev",
        playForFree: "It is free",
        mobileDesktop: "Desktop",
    },
    {
        description:
            "Ski down the most dangerous slopes without hitting the roadblocks in this endless HTML5 game.",
        gameCategory: "Sports & Racing",
        gameImage: "https://static.gamezop.com/EJaG_JfW9l/cover.jpg",
        gameTitle: "Groovy Ski",
        gameUrl: "https://9783.play.gamezop.com/g/EJaG_JfW9l",
        slug: "Groovy-Ski",
        metaUrl: "Groovy-Ski",
        view: 3,
        howToPlay: "Ski, but without hitting",
        whoCreated: "Hyopersonic",
        playForFree: "Join and play!",
        mobileDesktop: "You name it!!",
    },
    {
        description:
            "Karate out the enemies of our lone warrior fighting in the middle. But one miss and it's all over!",
        gameCategory: "Action",
        gameImage: "https://static.gamezop.com/Sy64_WbU/cover.jpg",
        gameTitle: "Punch Heroes",
        gameUrl: "https://9783.play.gamezop.com/g/Sy64_WbU",
        slug: "Punch-Heroes",
        metaUrl: "Punch-Heroes",
        view: 3,
        howToPlay: "Karate out your enemies",
        whoCreated: "Unknown",
        playForFree: "Totally free for you to use",
        mobileDesktop: "Any smart phone",
    },
    {
        description:
            "It's time to reveal the master of Darts! Focus, Aim, Precision... Bullseye!",
        gameCategory: "Sports & Racing",
        gameImage: "https://static.gamezop.com/SkF7yhp7q0B/cover.jpg",
        gameTitle: "Darts",
        gameUrl: "https://9783.play.gamezop.com/g/SkF7yhp7q0B",
        slug: "Darts",
        metaUrl: "Darts",
        view: 3,
        howToPlay: "You gotta use your aim!",
        whoCreated: "Innowise Group",
        playForFree: "Come here and play now!",
        mobileDesktop: "All devices",
    },
    {
        description:
            "Burst as many hexagons as you can - just don't kill the snake.",
        gameCategory: "Strategy",
        gameImage: "https://static.gamezop.com/H1abja2M_eb/cover.jpg",
        gameTitle: "Hex Burst",
        gameUrl: "https://9783.play.gamezop.com/g/H1abja2M_eb",
        slug: "Hex-Burst",
        metaUrl: "Hex-Burst",
        view: 3,
        howToPlay: "You have to burst many hexagon",
        whoCreated: "Korgi Inc",
        playForFree: "Gamezop",
        mobileDesktop: "Desktop",
    },
    {
        description:
            "Rumour has it that the unforgiving blade has been chopping veggies for years. Break its momentum.",
        gameCategory: "Arcade",
        gameImage: "https://static.gamezop.com/H1be5Ef0Qp/cover.jpg",
        gameTitle: "Vegetables vs. Chef",
        gameUrl: "https://9783.play.gamezop.com/g/H1be5Ef0Qp",
        slug: "Vegetables-vs-Chef",
        metaUrl: "Vegetables-vs-Chef",
        view: 3,
        howToPlay: "Have to chop vegetable",
        whoCreated: "Hypersonic",
        playForFree: "Click here",
        mobileDesktop: "Devices",
    },
    {
        description:
            "It's like the old-school snake but super flexi! If you're a snake game fan, this HTML5 game will delight you!",
        gameCategory: "Arcade",
        gameImage: "https://static.gamezop.com/SkQwnwnbK/cover.jpg",
        gameTitle: "Flexi Snake",
        gameUrl: "https://9783.play.gamezop.com/g/SkQwnwnbK",
        slug: "Flexi-Snake",
        metaUrl: "Flexi-Snake",
        view: 3,
        howToPlay: "Move snake and make it large",
        whoCreated: "Gamezop",
        playForFree: "Here is the place to play",
        mobileDesktop: "Tablet",
    },
    {
        description:
            "A fast-dodging, easy to play but hard to master bird game. Collect as many coins as possible.",
        gameCategory: "Arcade",
        gameImage: "https://static.gamezop.com/Hkww3v3-F/cover.jpg",
        gameTitle: "Fly Safe",
        gameUrl: "https://9783.play.gamezop.com/g/Hkww3v3-F",
        slug: "Fly-Safe",
        metaUrl: "Fly-Safe",
        view: 3,
        howToPlay: "Collect the coins",
        whoCreated: "Hypersonic",
        playForFree: "At Gamezop",
        mobileDesktop: "Phone",
    },
    {
        description:
            "Blast from barrel to barrel avoiding the yellow critters, reach as high as you can.",
        gameCategory: "Arcade",
        gameImage: "https://static.gamezop.com/ByvOVQZkK/cover.jpg",
        gameTitle: "Skill Shot",
        gameUrl: "https://9783.play.gamezop.com/g/ByvOVQZkK",
        slug: "Skill-Shot",
        metaUrl: "Skill-Shot",
        view: 3,
        howToPlay: "Reach high",
        whoCreated: "Korgi Lmt",
        playForFree: "Just click here",
        mobileDesktop: "Computer",
    },
    {
        description:
            "Is bartending on your bucket-list? Now's your chance! Serve your customers well.",
        gameCategory: "Arcade",
        gameImage: "https://static.gamezop.com/S1VZ-LjQUUl/cover.jpg",
        gameTitle: "Fizz Fuss",
        gameUrl: "https://9783.play.gamezop.com/g/S1VZ-LjQUUl",
        slug: "Fizz-Fuss",
        metaUrl: "Fizz-Fuss",
        view: 3,
        howToPlay: "Serve your customers well!",
        whoCreated: "Gamezop",
        playForFree: "Totally free for you to use!",
        mobileDesktop: "Mobile and desktp",
    },
    {
        description:
            "Slingshot your car in the corners and drift like a pro. Avoid crashing into the walls and score perfect turns that reward more points. Become the Drift King in this addictive and engaging take on drifting!",
        gameCategory: "Sports & Racing",
        gameImage: "https://static.gamezop.com/wIRrQjVa7/cover.jpg",
        gameTitle: "Hyperdrive Swinger",
        gameUrl: "https://9783.play.gamezop.com/g/wIRrQjVa7",
        slug: "Hyperdrive-Swinger",
        metaUrl: "Hyperdrive-Swinger",
        view: 3,
        howToPlay: "Drift like a pro! Avoid crashng into walls!",
        whoCreated: "Gamedev",
        playForFree: "It is all that you want, and for free",
        mobileDesktop: "Tablet, PC and Phone",
    },
];

const UploadGames = () => {
    const uploadGames = async () => {
        try {
            const gamesRef = ref(database, "/games");
            games.forEach(async (game) => {
                await push(gamesRef, game); // Push with a unique random ID
            });
            alert("Games uploaded successfully!");
        } catch (error) {
            console.error("Error uploading games:", error);
            alert("Failed to upload games.");
        }
    };

    return (
        <div>
            <button
                onClick={uploadGames}
                className="p-2 bg-blue-500 text-white rounded-md"
            >
                Upload Games
            </button>
        </div>
    );
};

export default UploadGames;
